const router = require('express').Router();
const auth = require('../../middlewares/auth');
const ctrl = require('../../controllers/api/productController');
router.use(auth);
router.post('/', ctrl.create);
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getOne);
router.put('/:id', ctrl.update);
router.delete('/:id', ctrl.remove);
module.exports = router;
